#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════════
//  LOCAL TRAINING SCRIPT - Train neural net weights for default AI
//  Usage: node scripts/train-local.js [generations] [popSize]
// ═══════════════════════════════════════════════════════════════════════════

import { Population } from "../shared/training.js";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const GENERATIONS = parseInt(process.argv[2]) || 30;
const POP_SIZE = parseInt(process.argv[3]) || 20;
const GAMES_PER_NET = 3;
const MAX_TICKS = 800;

console.log(`\n🧠 RTS Neural Net Training`);
console.log(`  Generations: ${GENERATIONS}`);
console.log(`  Population:  ${POP_SIZE}`);
console.log(`  Games/Net:   ${GAMES_PER_NET}`);
console.log(`  Max Ticks:   ${MAX_TICKS}`);
console.log(`  Total games: ~${GENERATIONS * POP_SIZE * GAMES_PER_NET}\n`);

const pop = new Population({
  size: POP_SIZE,
  mutationRate: 0.15,
  mutationStrength: 0.4,
});

let bestEver = -Infinity;
let bestWeightsEver = null;

const startTime = Date.now();

for (let g = 1; g <= GENERATIONS; g++) {
  const genStart = Date.now();
  const result = pop.runGeneration(GAMES_PER_NET, MAX_TICKS);
  const genMs = Date.now() - genStart;

  if (result.bestFitness > bestEver) {
    bestEver = result.bestFitness;
    bestWeightsEver = pop.getBest().toJSON();
  }

  const bar = "█".repeat(Math.max(0, Math.round(result.bestFitness / 10)));
  console.log(
    `Gen ${String(g).padStart(3)}/${GENERATIONS} | ` +
    `Best: ${result.bestFitness.toFixed(1).padStart(7)} | ` +
    `Avg: ${result.avgFitness.toFixed(1).padStart(7)} | ` +
    `${(genMs / 1000).toFixed(1)}s | ${bar}`
  );

  // Save checkpoint every 10 generations
  if (g % 10 === 0) {
    const checkpointPath = join(__dirname, `checkpoint-gen${g}.json`);
    writeFileSync(checkpointPath, JSON.stringify(bestWeightsEver));
    console.log(`  📁 Checkpoint saved: ${checkpointPath}`);
  }
}

const totalSec = ((Date.now() - startTime) / 1000).toFixed(1);
console.log(`\n✅ Training complete in ${totalSec}s`);
console.log(`  Best fitness ever: ${bestEver.toFixed(1)}`);

// Save best weights
const weightsPath = join(__dirname, "..", "shared", "default-weights.json");
writeFileSync(weightsPath, JSON.stringify(bestWeightsEver, null, 0));
console.log(`  Weights saved: ${weightsPath}`);

// Also save as a JS module for easy import
const modulePath = join(__dirname, "..", "shared", "default-weights.js");
writeFileSync(modulePath, `// Auto-generated by train-local.js - ${new Date().toISOString()}
// Best fitness: ${bestEver.toFixed(1)} after ${GENERATIONS} generations
export const DEFAULT_WEIGHTS = ${JSON.stringify(bestWeightsEver)};
`);
console.log(`  Module saved: ${modulePath}`);

// Save full population for continued training
const popPath = join(__dirname, "population.json");
writeFileSync(popPath, JSON.stringify(pop.toJSON()));
console.log(`  Population saved: ${popPath}`);
